ifneq (,$(filter nfc_generic,$(USEMODULE)))
  USEMODULE += nfc_ndef
  USEMODULE += nfc_t2t
  USEMODULE += nfc_t4t
endif
ifneq (,$(filter nfc_t2t,$(USEMODULE)))
  USEMODULE += nfc_ndef
endif
ifneq (,$(filter nfc_t4t,$(USEMODULE)))
  USEMODULE += nfc_ndef
endif
ifneq (,$(filter nfc_mifare,$(USEMODULE)))
  USEMODULE += nfc_ndef
endif
ifneq (,$(filter nfc_llcp,$(USEMODULE)))
  USEMODULE += nfc_llcp
endif


