ifneq (,$(filter nfc_generic,$(USEMODULE)))
  USEMODULE += nfc_ndef
  USEMODULE += nfc_t2t
  USEMODULE += nfc_t4t
  USEMODULE += nfc_mifare
endif
ifneq (,$(filter nfc_t2t,$(USEMODULE)))
  USEMODULE += nfc_ndef
  USEMODULE += nfc_tlv
endif
ifneq (,$(filter nfc_t4t,$(USEMODULE)))
  USEMODULE += nfc_ndef
endif
ifneq (,$(filter nfc_mifare,$(USEMODULE)))
  USEMODULE += nfc_ndef
endif
ifneq (,$(filter nfc_llcp,$(USEMODULE)))
  USEMODULE += tsrb
  USEMODULE += ztimer_msec
endif



