include ../Makefile.drivers_common

USEMODULE += st25

USEMODULE += periph_i2c
USEMOUDLE += periph_spi
USEMODULE += ztimer_usec

# suppress error -Werror=unused-function
CFLAGS += -Wno-error=unused-function


include $(RIOTBASE)/Makefile.include

